import {
  AccessLevel,
  AssessmentStatus,
  AssetType,
  BusinessArea,
  LifecycleStage,
  PrismaClient,
  RequestStatus,
  ReviewStatus,
  RiskLevel,
  Severity,
} from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.faqItem.deleteMany();
  await prisma.knowledgeSource.deleteMany();
  await prisma.agentDataAsset.deleteMany();
  await prisma.agentCapability.deleteMany();
  await prisma.agentDependency.deleteMany();
  await prisma.agentHook.deleteMany();
  await prisma.agentGuide.deleteMany();
  await prisma.agentRule.deleteMany();
  await prisma.agentSkill.deleteMany();
  await prisma.agentMcpServer.deleteMany();
  await prisma.mcpTool.deleteMany();
  await prisma.reviewItem.deleteMany();
  await prisma.savedItem.deleteMany();
  await prisma.accessRequest.deleteMany();
  await prisma.activity.deleteMany();
  await prisma.agent.deleteMany();
  await prisma.mcpServer.deleteMany();
  await prisma.skill.deleteMany();
  await prisma.rule.deleteMany();
  await prisma.guide.deleteMany();
  await prisma.hook.deleteMany();

  const mcpServers = await Promise.all([
    prisma.mcpServer.create({
      data: {
        slug: "sap-finance-mcp",
        name: "SAP Finance MCP",
        shortDescription: "Invoice, vendor and accounts payable tools for SAP S/4HANA.",
        description:
          "Enterprise MCP server exposing read and controlled write tools for SAP Finance processes including invoice lookup, vendor master retrieval and exception case creation.",
        origin: "Internal",
        owner: "Finance Integration Team",
        ownerEmail: "finance.integration@example.com",
        status: "Active",
        authType: "OAuth 2.0 / Service Principal",
        environments: "Dev, Test, Prod",
        riskLevel: RiskLevel.LOW,
        classification: "Internal",
        toolCount: 4,
        version: "1.4.2",
        endpoint: "https://mcp.internal.example/sap-finance",
        platform: "UPTIMIZE Agents",
        tags: "SAP,Finance,AP,MCP",
        tools: {
          create: [
            { name: "search_invoices", description: "Search invoices by vendor, amount or document ID." },
            { name: "get_vendor", description: "Retrieve vendor master data from SAP." },
            { name: "post_comment", description: "Add a workflow comment to an invoice case." },
            { name: "create_ticket", description: "Create an AP exception ticket." },
          ],
        },
      },
    }),
    prisma.mcpServer.create({
      data: {
        slug: "enterprise-search-mcp",
        name: "Enterprise Search MCP",
        shortDescription: "Cross-repository enterprise search across knowledge bases.",
        description:
          "Provides semantic and keyword search across approved internal knowledge sources with classification-aware filtering.",
        origin: "Internal",
        owner: "Knowledge Platform Team",
        ownerEmail: "knowledge.platform@example.com",
        status: "Active",
        authType: "SSO Token Exchange",
        environments: "Test, Prod",
        riskLevel: RiskLevel.LOW,
        classification: "Internal",
        toolCount: 3,
        version: "2.1.0",
        endpoint: "https://mcp.internal.example/enterprise-search",
        platform: "myGPT",
        tags: "Search,Knowledge,MCP",
        tools: {
          create: [
            { name: "search_knowledge", description: "Semantic search across approved corpora." },
            { name: "get_document", description: "Fetch a document by ID with ACL checks." },
            { name: "list_sources", description: "List searchable knowledge sources." },
          ],
        },
      },
    }),
    prisma.mcpServer.create({
      data: {
        slug: "servicenow-workflow-mcp",
        name: "ServiceNow Workflow MCP",
        shortDescription: "Create and update ServiceNow cases and workflows.",
        description:
          "MCP server for ServiceNow incident, request and case management used by automation and triage agents.",
        origin: "Internal",
        owner: "ITSM Automation",
        ownerEmail: "itsm.automation@example.com",
        status: "Active",
        authType: "API Key (vaulted)",
        environments: "Dev, Prod",
        riskLevel: RiskLevel.MEDIUM,
        classification: "Internal",
        toolCount: 3,
        version: "1.2.0",
        endpoint: "https://mcp.internal.example/servicenow",
        platform: "UPTIMIZE Agents",
        tags: "ServiceNow,ITSM,Workflow",
        tools: {
          create: [
            { name: "create_case", description: "Create a ServiceNow case." },
            { name: "update_case", description: "Update case status or fields." },
            { name: "get_case", description: "Retrieve case details." },
          ],
        },
      },
    }),
    prisma.mcpServer.create({
      data: {
        slug: "clinical-knowledge-mcp",
        name: "Clinical Knowledge MCP",
        shortDescription: "Clinical protocols, trial metadata and study documentation access.",
        description:
          "Controlled access to clinical knowledge assets for research and trial navigation agents.",
        origin: "Internal",
        owner: "Clinical Informatics",
        ownerEmail: "clinical.informatics@example.com",
        status: "Active",
        authType: "SSO + Role Claims",
        environments: "Test, Prod",
        riskLevel: RiskLevel.MEDIUM,
        classification: "Confidential",
        toolCount: 3,
        version: "0.9.5",
        endpoint: "https://mcp.internal.example/clinical-knowledge",
        platform: "HIVE",
        tags: "Clinical,Research,GxP",
        tools: {
          create: [
            { name: "search_protocols", description: "Search clinical protocols." },
            { name: "get_trial_metadata", description: "Retrieve trial metadata." },
            { name: "list_study_docs", description: "List approved study documents." },
          ],
        },
      },
    }),
    prisma.mcpServer.create({
      data: {
        slug: "sharepoint-content-mcp",
        name: "SharePoint Content MCP",
        shortDescription: "Read approved SharePoint sites and document libraries.",
        description:
          "Exposes read-only tools for approved SharePoint content with tenant ACL enforcement.",
        origin: "Internal",
        owner: "Collaboration Platforms",
        ownerEmail: "collab.platforms@example.com",
        status: "Active",
        authType: "Microsoft Entra ID",
        environments: "Prod",
        riskLevel: RiskLevel.LOW,
        classification: "Internal",
        toolCount: 2,
        version: "1.0.3",
        endpoint: "https://mcp.internal.example/sharepoint",
        platform: "Microsoft Copilot Studio",
        tags: "SharePoint,Documents,Content",
        tools: {
          create: [
            { name: "search_sites", description: "Search approved SharePoint sites." },
            { name: "get_file_metadata", description: "Retrieve file metadata." },
          ],
        },
      },
    }),
    prisma.mcpServer.create({
      data: {
        slug: "pubmed-research-mcp",
        name: "PubMed Research MCP",
        shortDescription: "Literature search and abstract retrieval via PubMed.",
        description:
          "Third-party research MCP for literature discovery used by scientific assistants.",
        origin: "Third-party",
        owner: "R&D Knowledge Services",
        ownerEmail: "rnd.knowledge@example.com",
        status: "Active",
        authType: "API Key (vaulted)",
        environments: "Prod",
        riskLevel: RiskLevel.LOW,
        classification: "Public",
        toolCount: 2,
        version: "3.0.1",
        endpoint: "https://mcp.internal.example/pubmed",
        platform: "myGPT",
        tags: "Research,PubMed,Literature",
        tools: {
          create: [
            { name: "search_literature", description: "Search PubMed literature." },
            { name: "get_abstract", description: "Retrieve publication abstract." },
          ],
        },
      },
    }),
  ]);

  const [sapMcp, searchMcp, snowMcp, clinicalMcp, sharepointMcp, pubmedMcp] = mcpServers;

  const skills = await Promise.all(
    [
      {
        slug: "document-classification",
        name: "Document Classification",
        shortDescription: "Classifies business documents into approved categories.",
        description: "Reusable skill for classifying invoices, contracts, SOPs and related document types.",
        category: "Document AI",
        owner: "Document Intelligence",
        ownerEmail: "doc.ai@example.com",
        version: "2.2.0",
        status: "Production",
        tags: "Classification,Documents",
      },
      {
        slug: "pdf-information-extraction",
        name: "PDF Information Extraction",
        shortDescription: "Extracts structured fields from PDF documents.",
        description: "OCR-assisted extraction of structured fields from PDFs with confidence scoring.",
        category: "Document AI",
        owner: "Document Intelligence",
        ownerEmail: "doc.ai@example.com",
        version: "1.8.1",
        status: "Production",
        tags: "OCR,Extraction,PDF",
      },
      {
        slug: "enterprise-search",
        name: "Enterprise Search",
        shortDescription: "Semantic search across approved enterprise knowledge.",
        description: "Composable search skill with ACL-aware ranking and source attribution.",
        category: "Knowledge",
        owner: "Knowledge Platform Team",
        ownerEmail: "knowledge.platform@example.com",
        version: "3.1.0",
        status: "Production",
        tags: "Search,RAG",
      },
      {
        slug: "vendor-matching",
        name: "Vendor Matching",
        shortDescription: "Matches invoice vendors to master data records.",
        description: "Fuzzy and rule-based vendor matching against SAP vendor master.",
        category: "Finance",
        owner: "Finance Integration Team",
        ownerEmail: "finance.integration@example.com",
        version: "1.3.0",
        status: "Production",
        tags: "Vendors,Matching,SAP",
      },
      {
        slug: "clinical-literature-search",
        name: "Clinical Literature Search",
        shortDescription: "Finds and ranks clinical literature for research questions.",
        description: "Literature search skill tailored to clinical and biomedical queries.",
        category: "Research",
        owner: "Clinical Informatics",
        ownerEmail: "clinical.informatics@example.com",
        version: "1.1.0",
        status: "Pilot",
        tags: "Clinical,Literature",
      },
      {
        slug: "summarization",
        name: "Summarization",
        shortDescription: "Produces concise summaries with source references.",
        description: "General-purpose summarization skill for documents and conversation outputs.",
        category: "Language",
        owner: "AI Platform Services",
        ownerEmail: "ai.platform@example.com",
        version: "4.0.0",
        status: "Production",
        tags: "Summarization,Language",
      },
      {
        slug: "translation",
        name: "Translation",
        shortDescription: "Translates enterprise content between approved languages.",
        description: "Translation skill with glossary support for regulated terminology.",
        category: "Language",
        owner: "AI Platform Services",
        ownerEmail: "ai.platform@example.com",
        version: "2.0.4",
        status: "Production",
        tags: "Translation,Language",
      },
      {
        slug: "human-escalation",
        name: "Human Escalation",
        shortDescription: "Routes low-confidence or high-risk actions to humans.",
        description: "Escalation skill that creates review tasks and notifies owners.",
        category: "Governance",
        owner: "AI Governance Office",
        ownerEmail: "ai.governance@example.com",
        version: "1.0.2",
        status: "Production",
        tags: "Escalation,HITL",
      },
      {
        slug: "policy-retrieval",
        name: "Policy Retrieval",
        shortDescription: "Retrieves relevant HR and corporate policies.",
        description: "Policy retrieval skill grounded in approved SharePoint and knowledge bases.",
        category: "Knowledge",
        owner: "HR Digital",
        ownerEmail: "hr.digital@example.com",
        version: "1.5.0",
        status: "Production",
        tags: "HR,Policy",
      },
      {
        slug: "anomaly-detection",
        name: "Anomaly Detection",
        shortDescription: "Flags unusual patterns in operational or quality data.",
        description: "Reusable anomaly scoring skill for quality and supplier risk scenarios.",
        category: "Analytics",
        owner: "Quality Analytics",
        ownerEmail: "quality.analytics@example.com",
        version: "0.8.0",
        status: "Pilot",
        tags: "Analytics,Risk",
      },
    ].map((s) => prisma.skill.create({ data: s }))
  );

  const [
    docClass,
    pdfExtract,
    enterpriseSearch,
    vendorMatching,
    clinicalLit,
    summarization,
    translation,
    humanEscalation,
    policyRetrieval,
    anomalyDetection,
  ] = skills;

  const rules = await Promise.all(
    [
      {
        slug: "sensitive-data-redaction",
        name: "Sensitive Data Redaction",
        shortDescription: "Redacts sensitive fields before model exposure or logging.",
        description: "Runtime guardrail that redacts PII and confidential fields from prompts, logs and tool outputs.",
        severity: Severity.HIGH,
        scope: "All agents handling Internal or Confidential data",
        status: "Active",
        owner: "AI Governance Office",
        ownerEmail: "ai.governance@example.com",
        policyCategory: "Data Protection",
        tags: "PII,Redaction,Guardrail",
      },
      {
        slug: "human-approval-high-value",
        name: "Human Approval for High-Value Actions",
        shortDescription: "Requires human approval for high-value financial actions.",
        description: "Blocks automated actions above configured monetary thresholds until human approval is recorded.",
        severity: Severity.CRITICAL,
        scope: "Finance and procurement agents",
        status: "Active",
        owner: "Finance Controls",
        ownerEmail: "finance.controls@example.com",
        policyCategory: "Human Oversight",
        tags: "Approval,Finance,HITL",
      },
      {
        slug: "approved-data-sources-only",
        name: "Approved Data Sources Only",
        shortDescription: "Restricts agents to approved data and knowledge sources.",
        description: "Ensures agents only query catalogued and approved knowledge/data sources.",
        severity: Severity.HIGH,
        scope: "Enterprise-wide",
        status: "Active",
        owner: "Data Governance",
        ownerEmail: "data.governance@example.com",
        policyCategory: "Data Governance",
        tags: "Sources,Governance",
      },
      {
        slug: "no-external-model-confidential",
        name: "No External Model for Confidential Data",
        shortDescription: "Prevents confidential data from leaving approved model endpoints.",
        description: "Blocks invocation of external models when data classification is Confidential or higher.",
        severity: Severity.CRITICAL,
        scope: "Agents with Confidential data",
        status: "Active",
        owner: "Cyber Security",
        ownerEmail: "cyber.security@example.com",
        policyCategory: "Cyber Security",
        tags: "Confidential,Models",
      },
      {
        slug: "prompt-injection-protection",
        name: "Prompt Injection Protection",
        shortDescription: "Detects and mitigates prompt injection patterns.",
        description: "Runtime checks for prompt injection and tool-chaining abuse patterns.",
        severity: Severity.HIGH,
        scope: "All conversational agents",
        status: "Active",
        owner: "Cyber Security",
        ownerEmail: "cyber.security@example.com",
        policyCategory: "Cyber Security",
        tags: "Security,Injection",
      },
      {
        slug: "pii-detection",
        name: "PII Detection",
        shortDescription: "Detects personal data in inputs and outputs.",
        description: "Scans agent inputs/outputs for personal data and enforces handling rules.",
        severity: Severity.HIGH,
        scope: "Enterprise-wide",
        status: "Active",
        owner: "Privacy Office",
        ownerEmail: "privacy.office@example.com",
        policyCategory: "Privacy",
        tags: "PII,Privacy",
      },
      {
        slug: "maximum-spend-per-run",
        name: "Maximum Spend per Run",
        shortDescription: "Enforces a maximum estimated cost per agent run.",
        description: "Stops or escalates runs that exceed configured cost thresholds.",
        severity: Severity.MEDIUM,
        scope: "Pay-per-use agents",
        status: "Active",
        owner: "AI Platform Services",
        ownerEmail: "ai.platform@example.com",
        policyCategory: "Cost Control",
        tags: "Cost,Spend",
      },
      {
        slug: "read-only-sap-access",
        name: "Read-Only SAP Access",
        shortDescription: "Limits SAP write tools unless explicitly approved.",
        description: "Default read-only SAP tool access with exception workflow for approved write actions.",
        severity: Severity.HIGH,
        scope: "SAP-connected agents",
        status: "Active",
        owner: "Finance Controls",
        ownerEmail: "finance.controls@example.com",
        policyCategory: "System Access",
        tags: "SAP,Read-Only",
      },
    ].map((r) => prisma.rule.create({ data: r }))
  );

  const [
    redaction,
    humanApproval,
    approvedSources,
    noExternalModel,
    promptInjection,
    piiDetection,
    maxSpend,
    readOnlySap,
  ] = rules;

  const guides = await Promise.all(
    [
      {
        slug: "how-to-register-an-ai-agent",
        name: "How to register an AI agent",
        shortDescription: "Step-by-step registration for new AI agents.",
        description: "Practical guide covering ownership, risk, metadata and approval readiness.",
        content:
          "## Purpose\nRegister agents so they can be discovered, governed and reused.\n\n## Steps\n1. Confirm business owner and backup owner.\n2. Capture use case, capability and platform.\n3. Complete risk and Responsible AI assessment.\n4. Link MCP servers, skills and rules.\n5. Submit for registration review.\n\n## Outcome\nThe agent appears in AI Agent Central with governance metadata.",
        category: "Onboarding",
        audience: "Agent owners",
        readingTimeMin: 8,
        tags: "Registration,Onboarding",
      },
      {
        slug: "ai-risk-assessment-guide",
        name: "AI Risk Assessment Guide",
        shortDescription: "How to classify and assess AI agent risk.",
        description: "Guidance for risk classification aligned to enterprise assessment practices.",
        content:
          "## Overview\nRisk assessment evaluates impact, data sensitivity, autonomy and oversight.\n\n## Key dimensions\n- Data classification and personal data\n- Autonomy level and actionability\n- Business criticality\n- Regulatory / GxP relevance\n\n## Outputs\nRisk level, assessment status and review cadence.",
        category: "Governance",
        audience: "Governance stakeholders",
        readingTimeMin: 12,
        tags: "Risk,Assessment",
      },
      {
        slug: "mcp-server-publishing-guide",
        name: "MCP Server Publishing Guide",
        shortDescription: "Publish reusable MCP servers for enterprise agents.",
        description: "Technical and governance checklist for MCP publication.",
        content:
          "## When to publish\nPublish MCP servers that provide reusable, authenticated enterprise tools.\n\n## Checklist\n- Owner and support contact\n- Auth model documented\n- Environments listed\n- Tools described\n- Classification and risk noted",
        category: "Technical",
        audience: "Platform engineers",
        readingTimeMin: 10,
        tags: "MCP,Publishing",
      },
      {
        slug: "responsible-ai-checklist",
        name: "Responsible AI Checklist",
        shortDescription: "Ethics and Responsible AI readiness checklist.",
        description: "Checklist covering fairness, transparency, oversight and documentation.",
        content:
          "## Checklist\n- Intended use documented\n- Limitations disclosed\n- Human oversight defined\n- Monitoring plan available\n- Escalation path defined",
        category: "Governance",
        audience: "All agent teams",
        readingTimeMin: 6,
        tags: "Responsible AI,Ethics",
      },
      {
        slug: "reuse-before-build-guide",
        name: "Reuse Before Build Guide",
        shortDescription: "Find existing capabilities before building new agents.",
        description: "Process guidance to reduce duplication across platforms.",
        content:
          "## Principle\nSearch AI Agent Central before creating a new agent.\n\n## Steps\n1. Search by outcome and capability.\n2. Compare platforms and risk.\n3. Request access or compose existing skills/MCP servers.\n4. Only then propose a new build.",
        category: "Discovery",
        audience: "Business & technical teams",
        readingTimeMin: 5,
        tags: "Reuse,Discovery",
      },
      {
        slug: "human-oversight-patterns",
        name: "Human Oversight Patterns",
        shortDescription: "Patterns for human-in-the-loop agent designs.",
        description: "Common oversight patterns for high-risk and high-value actions.",
        content:
          "## Patterns\n- Approval gates\n- Confidence-based escalation\n- Dual control for financial actions\n- Periodic sampling reviews",
        category: "Governance",
        audience: "Solution architects",
        readingTimeMin: 9,
        tags: "HITL,Oversight",
      },
      {
        slug: "production-readiness-checklist",
        name: "Production Readiness Checklist",
        shortDescription: "Checklist before promoting agents to production.",
        description: "Operational, security and governance readiness criteria.",
        content:
          "## Must-have\n- Owners assigned\n- Risk assessed\n- Monitoring enabled\n- Support contact defined\n- Rollback / shut-down path documented",
        category: "Operations",
        audience: "Agent owners",
        readingTimeMin: 7,
        tags: "Production,Readiness",
      },
      {
        slug: "agent-lifecycle-guide",
        name: "Agent Lifecycle Guide",
        shortDescription: "Lifecycle stages from idea to retirement.",
        description: "Defines Idea, Pilot, Production, Retiring and Retired stages.",
        content:
          "## Stages\n- Idea: concept and eligibility\n- Pilot: limited audience and monitoring\n- Production: governed reuse\n- Retiring: migration and notice\n- Retired: retained for audit only",
        category: "Lifecycle",
        audience: "All stakeholders",
        readingTimeMin: 8,
        tags: "Lifecycle,Process",
      },
    ].map((g) => prisma.guide.create({ data: g }))
  );

  const [registerGuide, riskGuide, mcpGuide, raiChecklist, reuseGuide, oversightGuide, prodChecklist, lifecycleGuide] =
    guides;

  const hooks = await Promise.all(
    [
      {
        slug: "risk-reassessment-on-tool-change",
        name: "Risk Reassessment on Tool Change",
        shortDescription: "Requires risk reassessment when tools or MCP servers change.",
        description: "Lifecycle automation that flags agents for reassessment when tool dependencies change.",
        triggerEvent: "agent.tools.updated",
        action: "Require risk reassessment",
        owner: "AI Governance Office",
        ownerEmail: "ai.governance@example.com",
        status: "Active",
        scope: "All production agents",
        enabled: true,
        tags: "Risk,Lifecycle",
      },
      {
        slug: "notify-owner-before-review",
        name: "Notify Owner Before Review",
        shortDescription: "Notifies owners ahead of scheduled governance reviews.",
        description: "Sends reminders to business and technical owners before review due dates.",
        triggerEvent: "agent.review.due_soon",
        action: "Notify business and technical owners",
        owner: "AI Governance Office",
        ownerEmail: "ai.governance@example.com",
        status: "Active",
        scope: "Enterprise-wide",
        enabled: true,
        tags: "Review,Notifications",
      },
      {
        slug: "disable-after-failed-cyber-review",
        name: "Disable Agent After Failed Cyber Review",
        shortDescription: "Disables agents that fail cyber review until remediated.",
        description: "Automatically sets access to restricted and flags lifecycle when cyber review fails.",
        triggerEvent: "agent.cyber_review.failed",
        action: "Disable agent and notify owners",
        owner: "Cyber Security",
        ownerEmail: "cyber.security@example.com",
        status: "Active",
        scope: "All agents",
        enabled: true,
        tags: "Cyber,Security",
      },
      {
        slug: "create-audit-event-on-publication",
        name: "Create Audit Event on Publication",
        shortDescription: "Writes an audit event when a new agent version is published.",
        description: "Creates immutable activity records for publication events.",
        triggerEvent: "agent.version.published",
        action: "Create audit activity event",
        owner: "Platform Operations",
        ownerEmail: "platform.ops@example.com",
        status: "Active",
        scope: "Enterprise-wide",
        enabled: true,
        tags: "Audit,Versioning",
      },
      {
        slug: "flag-high-cost-usage",
        name: "Flag High Cost Usage",
        shortDescription: "Flags unusually high monthly cost or token usage.",
        description: "Creates a review item when cost thresholds are exceeded.",
        triggerEvent: "agent.usage.cost_threshold",
        action: "Create cost review item",
        owner: "AI Platform Services",
        ownerEmail: "ai.platform@example.com",
        status: "Active",
        scope: "Pay-per-use agents",
        enabled: true,
        tags: "Cost,Usage",
      },
      {
        slug: "sync-metadata-after-new-version",
        name: "Sync Metadata After New Version",
        shortDescription: "Syncs catalog metadata after a new version is published.",
        description: "Keeps repository metadata aligned with platform registries after version updates.",
        triggerEvent: "agent.version.updated",
        action: "Sync catalog metadata",
        owner: "Platform Operations",
        ownerEmail: "platform.ops@example.com",
        status: "Active",
        scope: "Connected platforms",
        enabled: true,
        tags: "Metadata,Sync",
      },
    ].map((h) => prisma.hook.create({ data: h }))
  );

  const [riskReassessHook, notifyReviewHook, disableCyberHook, auditPublishHook, flagCostHook, syncMetaHook] = hooks;

  const daysFromNow = (days: number) => new Date(Date.now() + days * 24 * 60 * 60 * 1000);
  const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000);

  const invoice = await prisma.agent.create({
    data: {
      slug: "invoice-triage-agent",
      name: "Invoice Triage Agent",
      shortDescription:
        "Classifies incoming invoices, extracts relevant metadata and routes exceptions to the appropriate finance workflow.",
      description:
        "The Invoice Triage Agent supports Accounts Payable teams by classifying incoming invoices, extracting structured metadata, matching vendors and routing exceptions to the correct finance workflow. It is designed for reuse across Enabling Functions with clear human oversight for high-value actions.",
      agentId: "AGT-FIN-001",
      solutionType: "Agent Product",
      businessArea: BusinessArea.ENABLING_FUNCTIONS,
      businessCapability: "Accounts Payable",
      useCase: "Automate invoice intake classification and exception routing",
      businessCriticality: "High",
      valueBenefit: "Reduced manual triage effort and faster exception handling",
      costNote: "Estimated €1,850 / month at current volume",
      platform: "UPTIMIZE Foundry",
      lifecycleStage: LifecycleStage.PRODUCTION,
      registrationStatus: "Registered",
      approvalStatus: "Approved",
      businessOwner: "Anna Keller",
      businessOwnerEmail: "anna.keller@example.com",
      technicalOwner: "Marcus Weber",
      technicalOwnerEmail: "marcus.weber@example.com",
      backupOwner: "Lena Hoffmann",
      backupOwnerEmail: "lena.hoffmann@example.com",
      supportContact: "finance-ai-support@example.com",
      riskLevel: RiskLevel.LOW,
      riskAssessmentStatus: AssessmentStatus.ASSESSED,
      dataClassification: "Internal",
      personalData: false,
      gxpRelevant: false,
      cyberReviewStatus: "Approved",
      responsibleAiStatus: AssessmentStatus.ASSESSED,
      humanOversight: "Required",
      certified: true,
      accessLevel: AccessLevel.APPROVAL_REQUIRED,
      accessLeadTime: "2–3 business days",
      version: "2.3",
      framework: "UPTIMIZE Agent Runtime",
      model: "Enterprise LLM (approved endpoint)",
      autonomyLevel: "Assisted automation",
      invocationType: "Event-driven + API",
      environments: "Dev, Test, Prod",
      monthlyRuns: 1248,
      successRate: 97.4,
      averageLatencyMs: 1850,
      monthlyCost: "€1,850",
      rating: 4.8,
      ratingCount: 64,
      subscriberCount: 86,
      reviewCadence: "Annual",
      nextReviewAt: daysFromNow(43),
      tags: "Finance,Document AI,SAP,Production",
      featured: true,
      capabilityCategory: "Automation",
      usageLimitations: "Not intended for confidential HR or clinical documents",
      updatedAt: daysAgo(0),
      createdAt: daysAgo(180),
      capabilities: {
        create: [
          { name: "Document classification", description: "Classifies invoice document types." },
          { name: "Structured extraction", description: "Extracts vendor, amount, dates and line metadata." },
          { name: "Exception detection", description: "Detects missing fields and policy exceptions." },
          { name: "SAP lookup", description: "Looks up vendor and invoice references in SAP." },
          { name: "Human escalation", description: "Escalates low-confidence or high-value cases." },
        ],
      },
      dataAssets: {
        create: [
          { name: "SAP invoice metadata", description: "Invoice header and status fields", direction: "INPUT" },
          { name: "Uploaded invoice document", description: "PDF or image invoice payload", direction: "INPUT" },
          { name: "Vendor master data", description: "Approved vendor master records", direction: "INPUT" },
          { name: "Invoice classification", description: "Document class and confidence", direction: "OUTPUT" },
          { name: "Extracted fields", description: "Structured invoice fields", direction: "OUTPUT" },
          { name: "Routing recommendation", description: "Suggested AP workflow route", direction: "OUTPUT" },
        ],
      },
      knowledgeSources: {
        create: [
          { name: "Finance policy knowledge base", description: "AP policies and exception rules" },
          { name: "Vendor master", description: "SAP vendor reference data" },
          { name: "Accounts payable procedures", description: "Operational AP playbooks" },
        ],
      },
      faqItems: {
        create: [
          {
            question: "What is this agent intended for?",
            answer:
              "It supports Accounts Payable teams by classifying invoices, extracting metadata and routing exceptions. It is not a payment execution agent.",
          },
          {
            question: "Can this agent process personal data?",
            answer:
              "The current configuration is assessed for Internal business data without personal data processing. Contact the owner before expanding scope.",
          },
          {
            question: "How do I request access?",
            answer: "Use Request access on this page. Approvals are typically handled within 2–3 business days.",
          },
          {
            question: "What happens if the confidence score is low?",
            answer: "Low-confidence cases are escalated to a human reviewer via the Human Escalation skill.",
          },
        ],
      },
    },
  });

  const clinical = await prisma.agent.create({
    data: {
      slug: "clinical-trial-navigator",
      name: "Clinical Trial Navigator",
      shortDescription: "Helps clinical teams navigate trial protocols, study docs and operational questions.",
      description:
        "Clinical Trial Navigator assists clinical operations teams with protocol navigation, study documentation discovery and operational Q&A using approved clinical knowledge sources.",
      agentId: "AGT-HC-014",
      businessArea: BusinessArea.HEALTHCARE,
      businessCapability: "Clinical Operations",
      useCase: "Accelerate protocol and study documentation discovery",
      businessCriticality: "High",
      valueBenefit: "Faster answers for study teams with governed clinical knowledge",
      costNote: "Estimated €3,200 / month",
      platform: "HIVE",
      lifecycleStage: LifecycleStage.PILOT,
      businessOwner: "Sofia Ramirez",
      businessOwnerEmail: "sofia.ramirez@example.com",
      technicalOwner: "Jonas Brandt",
      technicalOwnerEmail: "jonas.brandt@example.com",
      backupOwner: "Priya Nair",
      backupOwnerEmail: "priya.nair@example.com",
      supportContact: "hive-clinical-support@example.com",
      riskLevel: RiskLevel.MEDIUM,
      riskAssessmentStatus: AssessmentStatus.ASSESSED,
      dataClassification: "Confidential",
      personalData: false,
      gxpRelevant: true,
      cyberReviewStatus: "Approved",
      responsibleAiStatus: AssessmentStatus.ASSESSED,
      humanOversight: "Required",
      certified: true,
      accessLevel: AccessLevel.RESTRICTED,
      accessLeadTime: "5 business days",
      version: "1.2",
      framework: "HIVE Agent Layer",
      model: "Enterprise LLM (approved endpoint)",
      autonomyLevel: "Advisory",
      invocationType: "Chat + retrieval",
      environments: "Test, Prod",
      monthlyRuns: 642,
      successRate: 94.1,
      averageLatencyMs: 2400,
      monthlyCost: "€3,200",
      rating: 4.9,
      ratingCount: 28,
      subscriberCount: 41,
      reviewCadence: "Semi-annual",
      nextReviewAt: daysFromNow(0),
      tags: "Clinical,Protocols,HIVE,Pilot",
      featured: true,
      capabilityCategory: "Research",
      updatedAt: daysAgo(1),
      createdAt: daysAgo(90),
      capabilities: {
        create: [
          { name: "Protocol navigation", description: "Locate and summarize protocol sections." },
          { name: "Study document discovery", description: "Find approved study documents." },
          { name: "Operational Q&A", description: "Answer operational questions with citations." },
          { name: "Literature assist", description: "Surface related clinical literature." },
        ],
      },
      dataAssets: {
        create: [
          { name: "Protocol query", description: "User question about a trial", direction: "INPUT" },
          { name: "Study identifiers", description: "Trial and protocol IDs", direction: "INPUT" },
          { name: "Cited answer", description: "Answer with document references", direction: "OUTPUT" },
          { name: "Document shortlist", description: "Ranked study documents", direction: "OUTPUT" },
        ],
      },
      knowledgeSources: {
        create: [
          { name: "Clinical protocol repository", description: "Approved protocol corpus" },
          { name: "Study document library", description: "Controlled study documentation" },
        ],
      },
      faqItems: {
        create: [
          {
            question: "What is this agent intended for?",
            answer: "Protocol navigation and study documentation discovery for authorized clinical teams.",
          },
          {
            question: "Can this agent process personal data?",
            answer: "No. It is configured for protocol and study documentation, not patient-level data.",
          },
          {
            question: "How do I request access?",
            answer: "Access is restricted. Submit a request and the clinical owner will review eligibility.",
          },
          {
            question: "What happens if the confidence score is low?",
            answer: "The agent returns a low-confidence notice and recommends human specialist review.",
          },
        ],
      },
    },
  });

  const supplier = await prisma.agent.create({
    data: {
      slug: "supplier-risk-copilot",
      name: "Supplier Risk Copilot",
      shortDescription: "Assists procurement teams in assessing supplier risk signals and follow-up actions.",
      description:
        "Supplier Risk Copilot consolidates supplier risk indicators and recommends follow-up actions for procurement specialists. Currently piloted in Microsoft Copilot Studio.",
      agentId: "AGT-PROC-007",
      businessArea: BusinessArea.ENABLING_FUNCTIONS,
      businessCapability: "Procurement",
      useCase: "Support supplier risk assessment with governed recommendations",
      businessCriticality: "Medium",
      valueBenefit: "Faster supplier risk triage and consistent follow-up",
      costNote: "Estimated €980 / month",
      platform: "Microsoft Copilot Studio",
      lifecycleStage: LifecycleStage.PILOT,
      businessOwner: "Thomas Berger",
      businessOwnerEmail: "thomas.berger@example.com",
      technicalOwner: "Elena Novak",
      technicalOwnerEmail: "elena.novak@example.com",
      backupOwner: "Chris Patel",
      backupOwnerEmail: "chris.patel@example.com",
      supportContact: "procurement-ai@example.com",
      riskLevel: RiskLevel.MEDIUM,
      riskAssessmentStatus: AssessmentStatus.PENDING,
      dataClassification: "Internal",
      personalData: false,
      gxpRelevant: false,
      cyberReviewStatus: "Pending",
      responsibleAiStatus: AssessmentStatus.PENDING,
      humanOversight: "Required",
      certified: false,
      accessLevel: AccessLevel.APPROVAL_REQUIRED,
      accessLeadTime: "3 business days",
      version: "0.7",
      framework: "Copilot Studio",
      model: "Microsoft Copilot models",
      autonomyLevel: "Advisory",
      invocationType: "Chat",
      environments: "Dev, Test",
      monthlyRuns: 312,
      successRate: 91.2,
      averageLatencyMs: 2100,
      monthlyCost: "€980",
      rating: 4.5,
      ratingCount: 17,
      subscriberCount: 22,
      reviewCadence: "Quarterly",
      nextReviewAt: daysAgo(5),
      tags: "Procurement,Risk,Copilot,Pilot",
      featured: true,
      capabilityCategory: "Data & Analytics",
      updatedAt: daysAgo(2),
      createdAt: daysAgo(60),
      capabilities: {
        create: [
          { name: "Risk signal aggregation", description: "Aggregates supplier risk indicators." },
          { name: "Follow-up recommendation", description: "Suggests next actions for buyers." },
          { name: "Anomaly highlighting", description: "Highlights unusual supplier patterns." },
        ],
      },
      dataAssets: {
        create: [
          { name: "Supplier profile", description: "Supplier master and category", direction: "INPUT" },
          { name: "Risk indicators", description: "Internal and external risk signals", direction: "INPUT" },
          { name: "Risk summary", description: "Narrative risk summary", direction: "OUTPUT" },
          { name: "Action list", description: "Recommended follow-ups", direction: "OUTPUT" },
        ],
      },
      knowledgeSources: {
        create: [
          { name: "Procurement risk playbooks", description: "Approved procurement guidance" },
          { name: "Supplier scorecards", description: "Historical supplier performance" },
        ],
      },
      faqItems: {
        create: [
          {
            question: "What is this agent intended for?",
            answer: "Advisory support for supplier risk triage in procurement.",
          },
          {
            question: "Can this agent process personal data?",
            answer: "No personal data processing is in scope for the current pilot.",
          },
          {
            question: "How do I request access?",
            answer: "Request access from this page. Approval is required while the agent is in pilot.",
          },
          {
            question: "What happens if the confidence score is low?",
            answer: "Recommendations are marked advisory-only and escalated to a procurement specialist.",
          },
        ],
      },
    },
  });

  const agentDefs = [
    {
      slug: "research-literature-assistant",
      name: "Research Literature Assistant",
      shortDescription: "Supports scientists with literature discovery and summarization.",
      description:
        "Helps R&D teams discover, summarize and compare scientific literature using approved research sources.",
      agentId: "AGT-LS-021",
      businessArea: BusinessArea.LIFE_SCIENCE,
      businessCapability: "Research",
      useCase: "Accelerate literature review for research teams",
      businessCriticality: "Medium",
      valueBenefit: "Reduced time-to-insight for literature reviews",
      platform: "myGPT",
      lifecycleStage: LifecycleStage.PRODUCTION,
      businessOwner: "Dr. Mira Chen",
      businessOwnerEmail: "mira.chen@example.com",
      technicalOwner: "Alex Foss",
      technicalOwnerEmail: "alex.foss@example.com",
      riskLevel: RiskLevel.LOW,
      riskAssessmentStatus: AssessmentStatus.ASSESSED,
      dataClassification: "Internal",
      personalData: false,
      gxpRelevant: false,
      cyberReviewStatus: "Approved",
      responsibleAiStatus: AssessmentStatus.ASSESSED,
      humanOversight: "Not required",
      certified: true,
      accessLevel: AccessLevel.OPEN,
      version: "3.1",
      monthlyRuns: 2104,
      successRate: 96.0,
      averageLatencyMs: 1900,
      monthlyCost: "€1,100",
      rating: 4.7,
      ratingCount: 89,
      subscriberCount: 154,
      nextReviewAt: daysFromNow(120),
      tags: "Research,Literature,myGPT",
      capabilityCategory: "Research",
      updatedAt: daysAgo(3),
    },
    {
      slug: "hr-policy-assistant",
      name: "HR Policy Assistant",
      shortDescription: "Answers HR policy questions using approved policy sources.",
      description:
        "Provides employees with grounded answers to HR policy questions and points to the authoritative policy documents.",
      agentId: "AGT-HR-004",
      businessArea: BusinessArea.ENABLING_FUNCTIONS,
      businessCapability: "HR",
      useCase: "Self-service HR policy guidance",
      businessCriticality: "Medium",
      valueBenefit: "Fewer repetitive HR tickets and faster employee answers",
      platform: "myGPT",
      lifecycleStage: LifecycleStage.PRODUCTION,
      businessOwner: "Julia Reinhardt",
      businessOwnerEmail: "julia.reinhardt@example.com",
      technicalOwner: "Noah Steiner",
      technicalOwnerEmail: "noah.steiner@example.com",
      riskLevel: RiskLevel.LOW,
      riskAssessmentStatus: AssessmentStatus.ASSESSED,
      dataClassification: "Internal",
      personalData: false,
      gxpRelevant: false,
      cyberReviewStatus: "Approved",
      responsibleAiStatus: AssessmentStatus.ASSESSED,
      humanOversight: "Required",
      certified: true,
      accessLevel: AccessLevel.OPEN,
      version: "2.0",
      monthlyRuns: 4580,
      successRate: 95.5,
      averageLatencyMs: 1600,
      monthlyCost: "€720",
      rating: 4.6,
      ratingCount: 201,
      subscriberCount: 890,
      nextReviewAt: daysFromNow(80),
      tags: "HR,Policy,myGPT",
      capabilityCategory: "HR & Productivity",
      updatedAt: daysAgo(4),
    },
    {
      slug: "quality-deviation-assistant",
      name: "Quality Deviation Assistant",
      shortDescription: "Supports quality teams investigating deviations and CAPA context.",
      description:
        "Assists quality teams by retrieving deviation context, related SOPs and suggested investigation next steps under human oversight.",
      agentId: "AGT-QA-011",
      businessArea: BusinessArea.HEALTHCARE,
      businessCapability: "Quality",
      useCase: "Support deviation investigation workflows",
      businessCriticality: "High",
      valueBenefit: "Faster investigation preparation with governed references",
      platform: "HIVE",
      lifecycleStage: LifecycleStage.PILOT,
      businessOwner: "Martin Vogt",
      businessOwnerEmail: "martin.vogt@example.com",
      technicalOwner: "Ines Braun",
      technicalOwnerEmail: "ines.braun@example.com",
      riskLevel: RiskLevel.HIGH,
      riskAssessmentStatus: AssessmentStatus.ASSESSED,
      dataClassification: "Confidential",
      personalData: false,
      gxpRelevant: true,
      cyberReviewStatus: "Approved",
      responsibleAiStatus: AssessmentStatus.ASSESSED,
      humanOversight: "Required",
      certified: false,
      accessLevel: AccessLevel.RESTRICTED,
      version: "0.9",
      monthlyRuns: 188,
      successRate: 89.4,
      averageLatencyMs: 2800,
      monthlyCost: "€1,450",
      rating: 4.2,
      ratingCount: 11,
      subscriberCount: 18,
      nextReviewAt: daysFromNow(20),
      tags: "Quality,Deviation,GxP,HIVE",
      capabilityCategory: "Data & Analytics",
      updatedAt: daysAgo(5),
    },
    {
      slug: "customer-insight-agent",
      name: "Customer Insight Agent",
      shortDescription: "Surfaces commercial insights from approved CRM knowledge.",
      description:
        "Helps commercial teams explore customer insights and account context from approved Salesforce knowledge.",
      agentId: "AGT-COM-009",
      businessArea: BusinessArea.HEALTHCARE,
      businessCapability: "Commercial",
      useCase: "Improve account preparation with CRM-grounded insights",
      businessCriticality: "Medium",
      valueBenefit: "Better meeting preparation and insight reuse",
      platform: "Salesforce",
      lifecycleStage: LifecycleStage.PILOT,
      businessOwner: "Nina Oswald",
      businessOwnerEmail: "nina.oswald@example.com",
      technicalOwner: "Derek Lang",
      technicalOwnerEmail: "derek.lang@example.com",
      riskLevel: RiskLevel.MEDIUM,
      riskAssessmentStatus: AssessmentStatus.PENDING,
      dataClassification: "Confidential",
      personalData: true,
      gxpRelevant: false,
      cyberReviewStatus: "Pending",
      responsibleAiStatus: AssessmentStatus.PENDING,
      humanOversight: "Required",
      certified: false,
      accessLevel: AccessLevel.APPROVAL_REQUIRED,
      version: "0.5",
      monthlyRuns: 240,
      successRate: 90.1,
      averageLatencyMs: 2200,
      monthlyCost: "€1,050",
      rating: 4.1,
      ratingCount: 9,
      subscriberCount: 15,
      nextReviewAt: daysFromNow(15),
      tags: "Commercial,CRM,Salesforce",
      capabilityCategory: "Customer Operations",
      updatedAt: daysAgo(6),
    },
    {
      slug: "sap-maintenance-copilot",
      name: "SAP Maintenance Copilot",
      shortDescription: "Assists manufacturing teams with SAP maintenance guidance.",
      description:
        "Provides guided recommendations for maintenance planners working in SAP-centric manufacturing contexts.",
      agentId: "AGT-MFG-003",
      businessArea: BusinessArea.ELECTRONICS,
      businessCapability: "Manufacturing",
      useCase: "Support maintenance planning and knowledge lookup",
      businessCriticality: "Medium",
      valueBenefit: "Reduced search time for maintenance procedures",
      platform: "SAP Joule",
      lifecycleStage: LifecycleStage.PILOT,
      businessOwner: "Ralf Meissner",
      businessOwnerEmail: "ralf.meissner@example.com",
      technicalOwner: "Helena Ortiz",
      technicalOwnerEmail: "helena.ortiz@example.com",
      riskLevel: RiskLevel.MEDIUM,
      riskAssessmentStatus: AssessmentStatus.ASSESSED,
      dataClassification: "Internal",
      personalData: false,
      gxpRelevant: false,
      cyberReviewStatus: "Approved",
      responsibleAiStatus: AssessmentStatus.ASSESSED,
      humanOversight: "Required",
      certified: false,
      accessLevel: AccessLevel.APPROVAL_REQUIRED,
      version: "1.0",
      monthlyRuns: 410,
      successRate: 92.8,
      averageLatencyMs: 2000,
      monthlyCost: "€1,300",
      rating: 4.3,
      ratingCount: 14,
      subscriberCount: 27,
      nextReviewAt: daysFromNow(55),
      tags: "Manufacturing,SAP,Joule",
      capabilityCategory: "Automation",
      updatedAt: daysAgo(7),
    },
    {
      slug: "automation-discovery-agent",
      name: "Automation Discovery Agent",
      shortDescription: "Identifies candidate processes for automation across teams.",
      description:
        "Helps process excellence teams discover automation candidates from process descriptions and usage signals.",
      agentId: "AGT-AUTO-001",
      businessArea: BusinessArea.GLOBAL_CROSS_SECTOR,
      businessCapability: "Process Automation",
      useCase: "Discover reusable automation opportunities",
      businessCriticality: "Low",
      valueBenefit: "Pipeline of reusable automation candidates",
      platform: "UiPath",
      lifecycleStage: LifecycleStage.IDEA,
      businessOwner: "Petra Lang",
      businessOwnerEmail: "petra.lang@example.com",
      technicalOwner: "Omar Hassan",
      technicalOwnerEmail: "omar.hassan@example.com",
      riskLevel: RiskLevel.NOT_ASSESSED,
      riskAssessmentStatus: AssessmentStatus.PENDING,
      dataClassification: "Internal",
      personalData: false,
      gxpRelevant: false,
      cyberReviewStatus: "Pending",
      responsibleAiStatus: AssessmentStatus.PENDING,
      humanOversight: "Required",
      certified: false,
      accessLevel: AccessLevel.OPEN,
      version: "0.1",
      monthlyRuns: 42,
      successRate: 0,
      averageLatencyMs: 0,
      monthlyCost: "n/a",
      rating: 0,
      ratingCount: 0,
      subscriberCount: 5,
      nextReviewAt: daysFromNow(30),
      tags: "Automation,UiPath,Idea",
      capabilityCategory: "Automation",
      updatedAt: daysAgo(8),
    },
    {
      slug: "regulatory-document-reviewer",
      name: "Regulatory Document Reviewer",
      shortDescription: "Supports regulatory teams reviewing document packages.",
      description:
        "Assists regulatory affairs with document package completeness checks and issue highlighting under strict human oversight.",
      agentId: "AGT-REG-008",
      businessArea: BusinessArea.HEALTHCARE,
      businessCapability: "Regulatory",
      useCase: "Support regulatory document package review",
      businessCriticality: "High",
      valueBenefit: "Earlier detection of package gaps before formal review",
      platform: "UPTIMIZE Agents",
      lifecycleStage: LifecycleStage.PRODUCTION,
      businessOwner: "Claudia Stein",
      businessOwnerEmail: "claudia.stein@example.com",
      technicalOwner: "Benito Ruiz",
      technicalOwnerEmail: "benito.ruiz@example.com",
      riskLevel: RiskLevel.HIGH,
      riskAssessmentStatus: AssessmentStatus.ASSESSED,
      dataClassification: "Confidential",
      personalData: false,
      gxpRelevant: true,
      cyberReviewStatus: "Approved",
      responsibleAiStatus: AssessmentStatus.ASSESSED,
      humanOversight: "Required",
      certified: true,
      accessLevel: AccessLevel.RESTRICTED,
      version: "1.6",
      monthlyRuns: 520,
      successRate: 93.7,
      averageLatencyMs: 3100,
      monthlyCost: "€2,700",
      rating: 4.4,
      ratingCount: 19,
      subscriberCount: 33,
      nextReviewAt: daysFromNow(40),
      tags: "Regulatory,Documents,UPTIMIZE",
      capabilityCategory: "Knowledge & Search",
      updatedAt: daysAgo(2),
    },
    {
      slug: "enterprise-knowledge-assistant",
      name: "Enterprise Knowledge Assistant",
      shortDescription: "Enterprise-wide knowledge assistant grounded in approved sources.",
      description:
        "Cross-sector knowledge assistant for discovering policies, guides and approved enterprise knowledge.",
      agentId: "AGT-KNOW-002",
      businessArea: BusinessArea.GLOBAL_CROSS_SECTOR,
      businessCapability: "Knowledge Management",
      useCase: "Unified knowledge discovery across approved sources",
      businessCriticality: "Medium",
      valueBenefit: "Reduced duplicate Q&A bots and faster knowledge findability",
      platform: "myGPT",
      lifecycleStage: LifecycleStage.PRODUCTION,
      businessOwner: "Sabine Holt",
      businessOwnerEmail: "sabine.holt@example.com",
      technicalOwner: "Kai Mendel",
      technicalOwnerEmail: "kai.mendel@example.com",
      riskLevel: RiskLevel.LOW,
      riskAssessmentStatus: AssessmentStatus.ASSESSED,
      dataClassification: "Internal",
      personalData: false,
      gxpRelevant: false,
      cyberReviewStatus: "Approved",
      responsibleAiStatus: AssessmentStatus.ASSESSED,
      humanOversight: "Not required",
      certified: true,
      accessLevel: AccessLevel.OPEN,
      version: "4.2",
      monthlyRuns: 8900,
      successRate: 96.8,
      averageLatencyMs: 1500,
      monthlyCost: "€2,100",
      rating: 4.7,
      ratingCount: 312,
      subscriberCount: 1450,
      nextReviewAt: daysFromNow(100),
      tags: "Knowledge,Search,myGPT",
      capabilityCategory: "Knowledge & Search",
      updatedAt: daysAgo(1),
    },
    {
      slug: "lab-investigation-assistant",
      name: "Lab Investigation Assistant",
      shortDescription: "Supports R&D lab teams investigating experimental anomalies.",
      description:
        "Assists lab scientists with investigation context, related experiments and literature pointers under pilot governance.",
      agentId: "AGT-RND-015",
      businessArea: BusinessArea.LIFE_SCIENCE,
      businessCapability: "R&D",
      useCase: "Support laboratory investigation workflows",
      businessCriticality: "Medium",
      valueBenefit: "Faster assembly of investigation context",
      platform: "HIVE",
      lifecycleStage: LifecycleStage.PILOT,
      businessOwner: "Dr. Hannah Frey",
      businessOwnerEmail: "hannah.frey@example.com",
      technicalOwner: "Leo Kang",
      technicalOwnerEmail: "leo.kang@example.com",
      riskLevel: RiskLevel.MEDIUM,
      riskAssessmentStatus: AssessmentStatus.ASSESSED,
      dataClassification: "Confidential",
      personalData: false,
      gxpRelevant: false,
      cyberReviewStatus: "Approved",
      responsibleAiStatus: AssessmentStatus.ASSESSED,
      humanOversight: "Required",
      certified: false,
      accessLevel: AccessLevel.APPROVAL_REQUIRED,
      version: "0.6",
      monthlyRuns: 155,
      successRate: 90.5,
      averageLatencyMs: 2600,
      monthlyCost: "€860",
      rating: 4.3,
      ratingCount: 8,
      subscriberCount: 12,
      nextReviewAt: daysFromNow(25),
      tags: "R&D,Lab,HIVE",
      capabilityCategory: "Research",
      updatedAt: daysAgo(9),
    },
    {
      slug: "vendor-matching-agent",
      name: "Vendor Matching Agent",
      shortDescription: "Specialized agent for matching vendors to master data records.",
      description:
        "Reusable agent asset focused on vendor matching. Often composed into broader finance agent products.",
      agentId: "AGT-FIN-002",
      businessArea: BusinessArea.ENABLING_FUNCTIONS,
      businessCapability: "Accounts Payable",
      useCase: "Match invoice vendors to SAP master data",
      businessCriticality: "Medium",
      valueBenefit: "Higher match accuracy for AP automation",
      platform: "UPTIMIZE Agents",
      lifecycleStage: LifecycleStage.PRODUCTION,
      businessOwner: "Anna Keller",
      businessOwnerEmail: "anna.keller@example.com",
      technicalOwner: "Marcus Weber",
      technicalOwnerEmail: "marcus.weber@example.com",
      riskLevel: RiskLevel.LOW,
      riskAssessmentStatus: AssessmentStatus.ASSESSED,
      dataClassification: "Internal",
      personalData: false,
      gxpRelevant: false,
      cyberReviewStatus: "Approved",
      responsibleAiStatus: AssessmentStatus.ASSESSED,
      humanOversight: "Required",
      certified: true,
      accessLevel: AccessLevel.OPEN,
      version: "1.4",
      monthlyRuns: 980,
      successRate: 98.1,
      averageLatencyMs: 900,
      monthlyCost: "€420",
      rating: 4.9,
      ratingCount: 22,
      subscriberCount: 40,
      nextReviewAt: daysFromNow(70),
      tags: "Finance,Vendors,Matching",
      capabilityCategory: "Automation",
      updatedAt: daysAgo(3),
    },
    {
      slug: "contract-clause-assistant",
      name: "Contract Clause Assistant",
      shortDescription: "Helps legal operations locate approved clause language.",
      description:
        "Supports legal operations by retrieving approved clause language and related guidance from governed sources.",
      agentId: "AGT-LEG-006",
      businessArea: BusinessArea.ENABLING_FUNCTIONS,
      businessCapability: "Legal Operations",
      useCase: "Accelerate approved clause discovery",
      businessCriticality: "Medium",
      valueBenefit: "Faster drafting with approved language",
      platform: "myGPT",
      lifecycleStage: LifecycleStage.PRODUCTION,
      businessOwner: "Eva Sommer",
      businessOwnerEmail: "eva.sommer@example.com",
      technicalOwner: "Paul Richter",
      technicalOwnerEmail: "paul.richter@example.com",
      riskLevel: RiskLevel.MEDIUM,
      riskAssessmentStatus: AssessmentStatus.ASSESSED,
      dataClassification: "Confidential",
      personalData: false,
      gxpRelevant: false,
      cyberReviewStatus: "Approved",
      responsibleAiStatus: AssessmentStatus.ASSESSED,
      humanOversight: "Required",
      certified: false,
      accessLevel: AccessLevel.APPROVAL_REQUIRED,
      version: "1.1",
      monthlyRuns: 670,
      successRate: 94.8,
      averageLatencyMs: 1700,
      monthlyCost: "€990",
      rating: 4.4,
      ratingCount: 26,
      subscriberCount: 48,
      nextReviewAt: daysFromNow(60),
      tags: "Legal,Contracts,myGPT",
      capabilityCategory: "Knowledge & Search",
      updatedAt: daysAgo(10),
    },
    {
      slug: "it-service-desk-copilot",
      name: "IT Service Desk Copilot",
      shortDescription: "Assists service desk agents with guided troubleshooting.",
      description:
        "Supports IT service desk agents with knowledge retrieval and guided troubleshooting recommendations.",
      agentId: "AGT-IT-012",
      businessArea: BusinessArea.ENABLING_FUNCTIONS,
      businessCapability: "IT Service Management",
      useCase: "Improve first-line resolution guidance",
      businessCriticality: "Medium",
      valueBenefit: "Faster ticket handling and consistent answers",
      platform: "UPTIMIZE Foundry",
      lifecycleStage: LifecycleStage.PRODUCTION,
      businessOwner: "Gregor Klein",
      businessOwnerEmail: "gregor.klein@example.com",
      technicalOwner: "Yara Solis",
      technicalOwnerEmail: "yara.solis@example.com",
      riskLevel: RiskLevel.LOW,
      riskAssessmentStatus: AssessmentStatus.ASSESSED,
      dataClassification: "Internal",
      personalData: true,
      gxpRelevant: false,
      cyberReviewStatus: "Approved",
      responsibleAiStatus: AssessmentStatus.ASSESSED,
      humanOversight: "Required",
      certified: true,
      accessLevel: AccessLevel.APPROVAL_REQUIRED,
      version: "2.1",
      monthlyRuns: 3200,
      successRate: 95.9,
      averageLatencyMs: 1400,
      monthlyCost: "€1,600",
      rating: 4.6,
      ratingCount: 74,
      subscriberCount: 210,
      nextReviewAt: daysFromNow(90),
      tags: "ITSM,ServiceDesk,UPTIMIZE",
      capabilityCategory: "Customer Operations",
      updatedAt: daysAgo(4),
    },
  ];

  const moreAgents = [];
  for (const def of agentDefs) {
    moreAgents.push(
      await prisma.agent.create({
        data: {
          ...def,
          framework: def.platform.includes("myGPT") ? "myGPT / Langdock" : def.platform,
          model: "Enterprise LLM (approved endpoint)",
          autonomyLevel: "Advisory",
          invocationType: "Chat",
          environments: "Test, Prod",
          reviewCadence: "Annual",
          backupOwner: "Backup Owner",
          backupOwnerEmail: "backup.owner@example.com",
          supportContact: "support@example.com",
          accessLeadTime: "2–5 business days",
          usageLimitations: "Demo scope only — fictional prototype record",
          createdAt: daysAgo(120),
          capabilities: {
            create: [
              { name: "Knowledge retrieval", description: "Retrieves approved knowledge for the use case." },
              { name: "Summarization", description: "Summarizes relevant content for the user." },
              { name: "Recommendation", description: "Provides governed recommendations." },
            ],
          },
          dataAssets: {
            create: [
              { name: "User query", description: "Natural language request", direction: "INPUT" },
              { name: "Context documents", description: "Approved knowledge context", direction: "INPUT" },
              { name: "Grounded response", description: "Answer with references", direction: "OUTPUT" },
            ],
          },
          knowledgeSources: {
            create: [{ name: "Approved knowledge base", description: "Governed knowledge corpus for this agent" }],
          },
          faqItems: {
            create: [
              {
                question: "What is this agent intended for?",
                answer: def.shortDescription,
              },
              {
                question: "Can this agent process personal data?",
                answer: def.personalData
                  ? "Yes, within a controlled and assessed scope."
                  : "No personal data processing is in the current assessed scope.",
              },
              {
                question: "How do I request access?",
                answer: "Use the Request access action on the agent detail page.",
              },
              {
                question: "What happens if the confidence score is low?",
                answer: "The agent escalates to a human reviewer or returns a low-confidence notice.",
              },
            ],
          },
        },
      })
    );
  }

  const vendorAgent = moreAgents.find((a) => a.slug === "vendor-matching-agent")!;
  const researchAgent = moreAgents.find((a) => a.slug === "research-literature-assistant")!;
  const hrAgent = moreAgents.find((a) => a.slug === "hr-policy-assistant")!;
  const knowledgeAgent = moreAgents.find((a) => a.slug === "enterprise-knowledge-assistant")!;
  const qualityAgent = moreAgents.find((a) => a.slug === "quality-deviation-assistant")!;
  const itsmAgent = moreAgents.find((a) => a.slug === "it-service-desk-copilot")!;

  // Relationships for Invoice Triage Agent
  await prisma.agentMcpServer.createMany({
    data: [
      { agentId: invoice.id, mcpServerId: sapMcp.id },
      { agentId: invoice.id, mcpServerId: snowMcp.id },
      { agentId: clinical.id, mcpServerId: clinicalMcp.id },
      { agentId: clinical.id, mcpServerId: pubmedMcp.id },
      { agentId: researchAgent.id, mcpServerId: pubmedMcp.id },
      { agentId: researchAgent.id, mcpServerId: searchMcp.id },
      { agentId: hrAgent.id, mcpServerId: sharepointMcp.id },
      { agentId: hrAgent.id, mcpServerId: searchMcp.id },
      { agentId: knowledgeAgent.id, mcpServerId: searchMcp.id },
      { agentId: knowledgeAgent.id, mcpServerId: sharepointMcp.id },
      { agentId: itsmAgent.id, mcpServerId: snowMcp.id },
      { agentId: itsmAgent.id, mcpServerId: searchMcp.id },
      { agentId: supplier.id, mcpServerId: searchMcp.id },
      { agentId: qualityAgent.id, mcpServerId: clinicalMcp.id },
    ],
  });

  await prisma.agentSkill.createMany({
    data: [
      { agentId: invoice.id, skillId: docClass.id },
      { agentId: invoice.id, skillId: pdfExtract.id },
      { agentId: invoice.id, skillId: vendorMatching.id },
      { agentId: invoice.id, skillId: humanEscalation.id },
      { agentId: clinical.id, skillId: clinicalLit.id },
      { agentId: clinical.id, skillId: summarization.id },
      { agentId: clinical.id, skillId: enterpriseSearch.id },
      { agentId: researchAgent.id, skillId: clinicalLit.id },
      { agentId: researchAgent.id, skillId: summarization.id },
      { agentId: researchAgent.id, skillId: translation.id },
      { agentId: hrAgent.id, skillId: policyRetrieval.id },
      { agentId: hrAgent.id, skillId: summarization.id },
      { agentId: knowledgeAgent.id, skillId: enterpriseSearch.id },
      { agentId: knowledgeAgent.id, skillId: summarization.id },
      { agentId: supplier.id, skillId: anomalyDetection.id },
      { agentId: supplier.id, skillId: summarization.id },
      { agentId: qualityAgent.id, skillId: anomalyDetection.id },
      { agentId: qualityAgent.id, skillId: humanEscalation.id },
      { agentId: vendorAgent.id, skillId: vendorMatching.id },
    ],
  });

  await prisma.agentRule.createMany({
    data: [
      { agentId: invoice.id, ruleId: redaction.id },
      { agentId: invoice.id, ruleId: humanApproval.id },
      { agentId: invoice.id, ruleId: readOnlySap.id },
      { agentId: clinical.id, ruleId: approvedSources.id },
      { agentId: clinical.id, ruleId: noExternalModel.id },
      { agentId: clinical.id, ruleId: promptInjection.id },
      { agentId: supplier.id, ruleId: piiDetection.id },
      { agentId: supplier.id, ruleId: maxSpend.id },
      { agentId: knowledgeAgent.id, ruleId: approvedSources.id },
      { agentId: knowledgeAgent.id, ruleId: promptInjection.id },
      { agentId: hrAgent.id, ruleId: redaction.id },
      { agentId: hrAgent.id, ruleId: approvedSources.id },
      { agentId: qualityAgent.id, ruleId: noExternalModel.id },
      { agentId: qualityAgent.id, ruleId: humanApproval.id },
    ],
  });

  await prisma.agentGuide.createMany({
    data: [
      { agentId: invoice.id, guideId: reuseGuide.id },
      { agentId: invoice.id, guideId: prodChecklist.id },
      { agentId: clinical.id, guideId: riskGuide.id },
      { agentId: clinical.id, guideId: raiChecklist.id },
      { agentId: supplier.id, guideId: oversightGuide.id },
      { agentId: knowledgeAgent.id, guideId: registerGuide.id },
      { agentId: vendorAgent.id, guideId: mcpGuide.id },
      { agentId: qualityAgent.id, guideId: lifecycleGuide.id },
    ],
  });

  await prisma.agentHook.createMany({
    data: [
      { agentId: invoice.id, hookId: riskReassessHook.id },
      { agentId: invoice.id, hookId: auditPublishHook.id },
      { agentId: clinical.id, hookId: notifyReviewHook.id },
      { agentId: supplier.id, hookId: flagCostHook.id },
      { agentId: qualityAgent.id, hookId: disableCyberHook.id },
      { agentId: knowledgeAgent.id, hookId: syncMetaHook.id },
    ],
  });

  await prisma.agentDependency.create({
    data: { agentId: invoice.id, dependsOnAgentId: vendorAgent.id },
  });

  await prisma.accessRequest.createMany({
    data: [
      {
        assetType: AssetType.AGENT,
        assetName: "Clinical Trial Navigator",
        assetSlug: "clinical-trial-navigator",
        agentId: clinical.id,
        reason: "Need protocol navigation for study startup",
        businessCase: "Clinical operations onboarding for Study NX-204",
        environment: "Prod",
        status: RequestStatus.PENDING,
        approver: "Sofia Ramirez",
        expectedAt: daysFromNow(3),
        requestedAt: daysAgo(1),
      },
      {
        assetType: AssetType.AGENT,
        assetName: "Supplier Risk Copilot",
        assetSlug: "supplier-risk-copilot",
        agentId: supplier.id,
        reason: "Pilot evaluation for category management",
        businessCase: "Evaluate supplier risk triage for Packaging category",
        environment: "Test",
        status: RequestStatus.APPROVED,
        approver: "Thomas Berger",
        expectedAt: daysAgo(2),
        requestedAt: daysAgo(8),
      },
      {
        assetType: AssetType.MCP_SERVER,
        assetName: "SAP Finance MCP",
        assetSlug: "sap-finance-mcp",
        reason: "Connect AP automation prototype",
        businessCase: "Reuse SAP Finance tools in a new AP workflow",
        environment: "Dev",
        status: RequestStatus.PENDING,
        approver: "Finance Integration Team",
        expectedAt: daysFromNow(5),
        requestedAt: daysAgo(2),
      },
      {
        assetType: AssetType.AGENT,
        assetName: "Quality Deviation Assistant",
        assetSlug: "quality-deviation-assistant",
        agentId: qualityAgent.id,
        reason: "Quality investigation support",
        businessCase: "Pilot for deviation investigation team",
        environment: "Test",
        status: RequestStatus.REJECTED,
        approver: "Martin Vogt",
        expectedAt: daysAgo(1),
        requestedAt: daysAgo(10),
      },
      {
        assetType: AssetType.AGENT,
        assetName: "Enterprise Knowledge Assistant",
        assetSlug: "enterprise-knowledge-assistant",
        agentId: knowledgeAgent.id,
        reason: "Team onboarding knowledge support",
        businessCase: "Provide onboarding Q&A for Enabling Functions",
        environment: "Prod",
        status: RequestStatus.APPROVED,
        approver: "Sabine Holt",
        expectedAt: daysAgo(4),
        requestedAt: daysAgo(12),
      },
      {
        assetType: AssetType.SKILL,
        assetName: "PDF Information Extraction",
        assetSlug: "pdf-information-extraction",
        reason: "Reuse extraction skill in document workflow",
        businessCase: "Compose extraction into a local automation",
        environment: "Dev",
        status: RequestStatus.PENDING,
        approver: "Document Intelligence",
        expectedAt: daysFromNow(4),
        requestedAt: daysAgo(0),
      },
    ],
  });

  await prisma.reviewItem.createMany({
    data: [
      {
        agentId: invoice.id,
        reason: "Annual review",
        dueDate: daysFromNow(43),
        status: ReviewStatus.DUE_SOON,
      },
      {
        agentId: clinical.id,
        reason: "Model version changed",
        dueDate: daysFromNow(0),
        status: ReviewStatus.OPEN,
      },
      {
        agentId: supplier.id,
        reason: "New data source detected",
        dueDate: daysAgo(5),
        status: ReviewStatus.OVERDUE,
      },
      {
        agentId: qualityAgent.id,
        reason: "GxP readiness checkpoint",
        dueDate: daysFromNow(20),
        status: ReviewStatus.OPEN,
      },
      {
        agentId: knowledgeAgent.id,
        reason: "Periodic certification renewal",
        dueDate: daysFromNow(100),
        status: ReviewStatus.OPEN,
      },
    ],
  });

  await prisma.activity.createMany({
    data: [
      {
        title: "Risk assessment renewed",
        description: "Risk classification confirmed as Low for Invoice Triage Agent.",
        actor: "AI Governance Office",
        assetType: AssetType.AGENT,
        assetName: "Invoice Triage Agent",
        assetSlug: "invoice-triage-agent",
        agentId: invoice.id,
        createdAt: daysAgo(0),
      },
      {
        title: "Agent v2.3 published",
        description: "Invoice Triage Agent version 2.3 published to production.",
        actor: "Marcus Weber",
        assetType: AssetType.AGENT,
        assetName: "Invoice Triage Agent",
        assetSlug: "invoice-triage-agent",
        agentId: invoice.id,
        createdAt: daysAgo(1),
      },
      {
        title: "MCP server dependency registered",
        description: "ServiceNow Workflow MCP linked to Invoice Triage Agent.",
        actor: "Platform Operations",
        assetType: AssetType.MCP_SERVER,
        assetName: "ServiceNow Workflow MCP",
        assetSlug: "servicenow-workflow-mcp",
        agentId: invoice.id,
        mcpServerId: snowMcp.id,
        createdAt: daysAgo(2),
      },
      {
        title: "Business owner updated",
        description: "Business owner set to Sofia Ramirez for Clinical Trial Navigator.",
        actor: "HIVE Platform",
        assetType: AssetType.AGENT,
        assetName: "Clinical Trial Navigator",
        assetSlug: "clinical-trial-navigator",
        agentId: clinical.id,
        createdAt: daysAgo(2),
      },
      {
        title: "Agent certified",
        description: "Invoice Triage Agent received certification stamp.",
        actor: "AI Governance Office",
        assetType: AssetType.AGENT,
        assetName: "Invoice Triage Agent",
        assetSlug: "invoice-triage-agent",
        agentId: invoice.id,
        createdAt: daysAgo(3),
      },
      {
        title: "Access granted",
        description: "Access approved for Supplier Risk Copilot pilot evaluation.",
        actor: "Thomas Berger",
        assetType: AssetType.AGENT,
        assetName: "Supplier Risk Copilot",
        assetSlug: "supplier-risk-copilot",
        agentId: supplier.id,
        createdAt: daysAgo(4),
      },
      {
        title: "Risk classification updated",
        description: "Quality Deviation Assistant classified as High Risk.",
        actor: "AI Governance Office",
        assetType: AssetType.AGENT,
        assetName: "Quality Deviation Assistant",
        assetSlug: "quality-deviation-assistant",
        agentId: qualityAgent.id,
        createdAt: daysAgo(5),
      },
      {
        title: "New MCP dependency registered",
        description: "PubMed Research MCP registered and linked to research agents.",
        actor: "R&D Knowledge Services",
        assetType: AssetType.MCP_SERVER,
        assetName: "PubMed Research MCP",
        assetSlug: "pubmed-research-mcp",
        mcpServerId: pubmedMcp.id,
        createdAt: daysAgo(6),
      },
      {
        title: "Agent deprecated notice",
        description: "Automation Discovery Agent remains in Idea stage pending assessment.",
        actor: "Platform Operations",
        assetType: AssetType.AGENT,
        assetName: "Automation Discovery Agent",
        assetSlug: "automation-discovery-agent",
        createdAt: daysAgo(7),
      },
      {
        title: "Skill published",
        description: "Human Escalation skill published for reuse.",
        actor: "AI Governance Office",
        assetType: AssetType.SKILL,
        assetName: "Human Escalation",
        assetSlug: "human-escalation",
        createdAt: daysAgo(8),
      },
      {
        title: "Rule activated",
        description: "No External Model for Confidential Data activated enterprise-wide.",
        actor: "Cyber Security",
        assetType: AssetType.RULE,
        assetName: "No External Model for Confidential Data",
        assetSlug: "no-external-model-confidential",
        createdAt: daysAgo(9),
      },
      {
        title: "Hook enabled",
        description: "Risk Reassessment on Tool Change enabled for production agents.",
        actor: "AI Governance Office",
        assetType: AssetType.HOOK,
        assetName: "Risk Reassessment on Tool Change",
        assetSlug: "risk-reassessment-on-tool-change",
        createdAt: daysAgo(10),
      },
      {
        title: "Guide updated",
        description: "Reuse Before Build Guide refreshed with discovery steps.",
        actor: "AI Platform Services",
        assetType: AssetType.GUIDE,
        assetName: "Reuse Before Build Guide",
        assetSlug: "reuse-before-build-guide",
        createdAt: daysAgo(11),
      },
      {
        title: "Metadata synced",
        description: "Enterprise Knowledge Assistant metadata synced after version 4.2.",
        actor: "Platform Operations",
        assetType: AssetType.AGENT,
        assetName: "Enterprise Knowledge Assistant",
        assetSlug: "enterprise-knowledge-assistant",
        agentId: knowledgeAgent.id,
        createdAt: daysAgo(1),
      },
      {
        title: "Access request submitted",
        description: "Access requested for Clinical Trial Navigator.",
        actor: "Christina H.",
        assetType: AssetType.AGENT,
        assetName: "Clinical Trial Navigator",
        assetSlug: "clinical-trial-navigator",
        agentId: clinical.id,
        createdAt: daysAgo(1),
      },
    ],
  });

  await prisma.savedItem.createMany({
    data: [
      {
        assetType: AssetType.AGENT,
        assetId: invoice.id,
        assetSlug: invoice.slug,
        assetName: invoice.name,
        agentId: invoice.id,
      },
      {
        assetType: AssetType.MCP_SERVER,
        assetId: sapMcp.id,
        assetSlug: sapMcp.slug,
        assetName: sapMcp.name,
        mcpServerId: sapMcp.id,
      },
      {
        assetType: AssetType.SKILL,
        assetId: pdfExtract.id,
        assetSlug: pdfExtract.slug,
        assetName: pdfExtract.name,
        skillId: pdfExtract.id,
      },
    ],
  });

  console.log("Seed completed successfully.");
  console.log(
    `Agents: ${1 + 1 + 1 + moreAgents.length}, MCP: ${mcpServers.length}, Skills: ${skills.length}, Rules: ${rules.length}`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
