import { Suspense } from "react";
import { prisma } from "@/lib/db";
import { BrowseClient, type BrowseItem } from "@/components/browse/BrowseClient";
import {
  accessLabels,
  businessAreaLabels,
  lifecycleLabels,
} from "@/lib/labels";

export const dynamic = "force-dynamic";

export default async function BrowsePage() {
  const [
    agents,
    products,
    useCases,
    mcps,
    skills,
    rules,
    guides,
    hooks,
    dataAssets,
    dataProducts,
    glossary,
    domains,
  ] = await Promise.all([
    prisma.agent.findMany({ orderBy: { rating: "desc" } }),
    prisma.agentProduct.findMany({ orderBy: { rating: "desc" } }),
    prisma.useCase.findMany({ orderBy: { useCaseId: "asc" } }),
    prisma.mcpServer.findMany({ orderBy: { updatedAt: "desc" } }),
    prisma.skill.findMany({ orderBy: { updatedAt: "desc" } }),
    prisma.rule.findMany({ orderBy: { updatedAt: "desc" } }),
    prisma.guide.findMany({ orderBy: { updatedAt: "desc" } }),
    prisma.hook.findMany({ orderBy: { updatedAt: "desc" } }),
    prisma.catalogDataAsset.findMany({ orderBy: { updatedAt: "desc" } }),
    prisma.catalogDataProduct.findMany({ orderBy: { updatedAt: "desc" } }),
    prisma.glossaryTerm.findMany({ orderBy: { name: "asc" } }),
    prisma.dataDomain.findMany({ orderBy: { name: "asc" } }),
  ]);

  const items: BrowseItem[] = [
    ...agents.map((a) => ({
      id: a.id,
      slug: a.slug,
      name: a.name,
      type: "AGENT" as const,
      typeLabel: "AI Agent",
      href: `/agents/${a.slug}`,
      subtitle: `${a.businessCapability} · ${businessAreaLabels[a.businessArea]}`,
      description: a.shortDescription,
      tags: a.useCaseId ? `${a.tags},usecase-linked` : a.tags,
      rating: a.rating,
      platform: a.platform,
      riskLevel: a.riskLevel,
      certified: a.certified,
      businessArea: businessAreaLabels[a.businessArea],
      businessCapability: a.businessCapability,
      lifecycle: lifecycleLabels[a.lifecycleStage],
      access: accessLabels[a.accessLevel],
      accessLevel: a.accessLevel,
      trust: a.certified
        ? "Certified"
        : a.riskAssessmentStatus === "ASSESSED"
          ? "Assessed"
          : a.riskAssessmentStatus === "EXPIRED"
            ? "Expired"
            : "Pending",
      updatedAt: a.updatedAt.toISOString(),
      monthlyRuns: a.monthlyRuns,
      owner: a.businessOwner,
      cost: a.monthlyCost || a.costNote || undefined,
      usagePolicy: a.usagePolicy,
      valueBenefit: a.valueBenefit,
      agentId: a.agentId,
      framework: a.framework || undefined,
      model: a.model || undefined,
      version: a.version,
      agentPattern: a.agentPattern,
      solutionType: a.solutionType,
      originType: a.originType,
      visibility: a.visibility,
    })),
    ...products.map((p) => ({
      id: p.id,
      slug: p.slug,
      name: p.name,
      type: "AGENT_PRODUCT" as const,
      typeLabel: "Agent Product",
      href: `/agent-products/${p.slug}`,
      subtitle: `${p.businessCapability} · ${businessAreaLabels[p.businessArea]}`,
      description: p.shortDescription,
      tags: p.useCaseId ? `${p.tags},usecase-linked` : p.tags,
      rating: p.rating,
      platform: p.platform || undefined,
      riskLevel: p.riskLevel,
      certified: p.certified,
      businessArea: businessAreaLabels[p.businessArea],
      businessCapability: p.businessCapability,
      lifecycle: lifecycleLabels[p.lifecycleStage],
      access: accessLabels[p.accessLevel],
      accessLevel: p.accessLevel,
      trust: p.certified ? "Certified" : "Assessed",
      updatedAt: p.updatedAt.toISOString(),
      owner: p.businessOwner,
      usagePolicy: p.usagePolicy,
      valueBenefit: p.valueBenefit,
      solutionType: "Agent Product",
      originType: "Internal",
    })),
    ...useCases.map((u) => ({
      id: u.id,
      slug: u.slug,
      name: u.name,
      type: "USE_CASE" as const,
      typeLabel: "Use Case",
      href: `/use-cases/${u.slug}`,
      subtitle: `${u.useCaseId} · ${businessAreaLabels[u.businessArea]}`,
      description: u.description,
      tags: `${u.tags},usecase-linked`,
      platform: u.platform || undefined,
      riskLevel: u.riskLevel,
      businessArea: businessAreaLabels[u.businessArea],
      businessCapability: u.businessCapability,
      lifecycle: lifecycleLabels[u.lifecycle],
      trust: u.riskAssessmentStatus === "ASSESSED" ? "Assessed" : u.riskAssessmentStatus === "EXPIRED" ? "Expired" : "Pending",
      updatedAt: u.updatedAt.toISOString(),
      owner: u.owner,
    })),
    ...mcps.map((m) => ({
      id: m.id,
      slug: m.slug,
      name: m.name,
      type: "MCP_SERVER" as const,
      typeLabel: "MCP Server",
      href: `/mcp-servers/${m.slug}`,
      subtitle: `${m.origin} · ${m.status}`,
      description: m.shortDescription,
      tags: m.tags,
      platform: m.platform || undefined,
      riskLevel: m.riskLevel,
      lifecycle: m.status,
      trust: m.riskLevel === "NOT_ASSESSED" ? "Pending" : "Assessed",
      updatedAt: m.updatedAt.toISOString(),
      owner: m.owner,
      originType: m.origin.includes("Third") ? "External / Third Party" : "Internal",
      version: m.version,
    })),
    ...skills.map((s) => ({
      id: s.id,
      slug: s.slug,
      name: s.name,
      type: "SKILL" as const,
      typeLabel: "Skill",
      href: `/skills/${s.slug}`,
      subtitle: `${s.category} · ${s.status}`,
      description: s.shortDescription,
      tags: s.tags,
      updatedAt: s.updatedAt.toISOString(),
      trust: s.status === "Production" ? "Assessed" : "Pending",
      owner: s.owner,
      version: s.version,
    })),
    ...rules.map((r) => ({
      id: r.id,
      slug: r.slug,
      name: r.name,
      type: "RULE" as const,
      typeLabel: "Rule",
      href: `/rules/${r.slug}`,
      subtitle: `${r.policyCategory} · ${r.status}`,
      description: r.shortDescription,
      tags: r.tags,
      updatedAt: r.updatedAt.toISOString(),
      trust: "Assessed",
      owner: r.owner,
    })),
    ...guides.map((g) => ({
      id: g.id,
      slug: g.slug,
      name: g.name,
      type: "GUIDE" as const,
      typeLabel: "Guide",
      href: `/guides/${g.slug}`,
      subtitle: `${g.category} · ${g.audience}`,
      description: g.shortDescription,
      tags: g.tags,
      updatedAt: g.updatedAt.toISOString(),
    })),
    ...hooks.map((h) => ({
      id: h.id,
      slug: h.slug,
      name: h.name,
      type: "HOOK" as const,
      typeLabel: "Hook",
      href: `/hooks/${h.slug}`,
      subtitle: `${h.scope} · ${h.status}`,
      description: h.shortDescription,
      tags: h.tags,
      updatedAt: h.updatedAt.toISOString(),
      owner: h.owner,
    })),
    ...dataAssets.map((a) => ({
      id: a.id,
      slug: a.slug,
      name: a.name,
      type: "DATA_ASSET" as const,
      typeLabel: "Data Asset",
      href: `/data-assets/${a.slug}`,
      subtitle: `${a.assetType} · ${a.domainName}`,
      description: a.shortDescription,
      tags: a.tags,
      updatedAt: a.updatedAt.toISOString(),
      owner: a.owner,
      platform: a.sourceSystem,
    })),
    ...dataProducts.map((p) => ({
      id: p.id,
      slug: p.slug,
      name: p.name,
      type: "DATA_PRODUCT" as const,
      typeLabel: "Data Product",
      href: `/data-products/${p.slug}`,
      subtitle: p.domainName,
      description: p.shortDescription,
      tags: p.tags,
      rating: p.rating,
      platform: p.platform || undefined,
      updatedAt: p.updatedAt.toISOString(),
      owner: p.owner,
    })),
    ...glossary.map((g) => ({
      id: g.id,
      slug: g.slug,
      name: g.name,
      type: "GLOSSARY_TERM" as const,
      typeLabel: "Glossary Term",
      href: `/glossary/${g.slug}`,
      subtitle: g.category,
      description: g.shortDescription,
      tags: g.tags,
      updatedAt: g.updatedAt.toISOString(),
    })),
    ...domains.map((d) => ({
      id: d.id,
      slug: d.slug,
      name: d.name,
      type: "DATA_DOMAIN" as const,
      typeLabel: "Data Domain",
      href: `/data-domains/${d.slug}`,
      subtitle: d.owner,
      description: d.description,
      tags: d.tags,
      updatedAt: d.updatedAt.toISOString(),
      owner: d.owner,
    })),
  ];

  return (
    <Suspense fallback={<div className="text-sm text-muted">Loading browse…</div>}>
      <BrowseClient items={items} />
    </Suspense>
  );
}
